// circle_usb_shim.cpp
//
// Thin C++ shim that wraps Circle's USB HID keyboard and mouse classes
// with extern "C" functions callable from Rust via FFI.
//
// Circle provides:
//   - CXHCIDevice  — xHCI host controller (VL805 over PCIe on Pi 4)
//   - CInterruptSystem — ARM GIC interrupt controller
//   - CTimer           — system timer
//   - CUSBKeyboardDevice — HID keyboard (raw + cooked mode)
//   - CMouseDevice      — HID mouse (raw mode via status handler)
//   - CDeviceNameService — device registry ("ukbd1", "mouse1")
//
// The shim exposes six C functions:
//   circle_usb_init()        — init interrupt, timer, xHCI; scan devices
//   circle_usb_update()      — call UpdatePlugAndPlay() and try to bind devices
//   circle_keyboard_getc()   — return next ASCII char (0 = none available)
//   circle_keyboard_ready()  — 1 if keyboard is connected
//   circle_mouse_get_state() — fill a MouseState struct
//   circle_mouse_ready()     — 1 if mouse is connected

#include <circle/interrupt.h>
#include <circle/timer.h>
#include <circle/devicenameservice.h>
#include <circle/usb/usbhcidevice.h>
#include <circle/usb/usbkeyboard.h>
#include <circle/input/mouse.h>
#include <circle/types.h>

// ─── Shared state ─────────────────────────────────────────────────────────────

// Circle objects — allocated statically to avoid heap dependency at startup.
// These are large objects; they live in BSS (zero-initialised).
static CInterruptSystem  s_Interrupt;
static CTimer            s_Timer (&s_Interrupt);
static CDeviceNameService s_DeviceNameService;

// CUSBHCIDevice is CXHCIDevice on Pi 4 (defined via the usbhcidevice.h alias).
// TRUE = enable plug-and-play (hot-plug detection).
static CUSBHCIDevice     s_USBHCI (&s_Interrupt, &s_Timer, TRUE);

static CUSBKeyboardDevice *s_pKeyboard = nullptr;
static CMouseDevice       *s_pMouse    = nullptr;

// ─── Keyboard ring buffer ─────────────────────────────────────────────────────
// Circle calls our handler from interrupt context; we queue chars here.

static volatile char  s_KeyBuf[64];
static volatile int   s_KeyHead = 0;
static volatile int   s_KeyTail = 0;

static void key_push(char c) {
    int next = (s_KeyHead + 1) % 64;
    if (next != s_KeyTail) {
        s_KeyBuf[s_KeyHead] = c;
        s_KeyHead = next;
    }
}

static char key_pop() {
    if (s_KeyHead == s_KeyTail) return 0;
    char c = s_KeyBuf[s_KeyTail];
    s_KeyTail = (s_KeyTail + 1) % 64;
    return c;
}

// ─── Mouse state ──────────────────────────────────────────────────────────────

static volatile unsigned s_MouseButtons = 0;
static volatile int      s_MouseX       = 0;
static volatile int      s_MouseY       = 0;
static volatile int      s_MouseDX      = 0;
static volatile int      s_MouseDY      = 0;

// ─── Circle callbacks ─────────────────────────────────────────────────────────

// Called by Circle's keyboard driver (cooked mode) with a null-terminated
// string of characters generated by the key press.
static void KeyPressedHandler(const char *pString) {
    while (*pString) {
        key_push(*pString++);
    }
}

// Called by Circle's mouse driver (raw mode) with displacement values.
static void MouseStatusHandler(unsigned nButtons,
                                int nDisplacementX,
                                int nDisplacementY,
                                int nWheelMove) {
    s_MouseButtons = nButtons;
    s_MouseDX = nDisplacementX;
    s_MouseDY = nDisplacementY;
    s_MouseX += nDisplacementX;
    s_MouseY += nDisplacementY;
    // Clamp to reasonable screen bounds
    if (s_MouseX < 0)    s_MouseX = 0;
    if (s_MouseX > 1919) s_MouseX = 1919;
    if (s_MouseY < 0)    s_MouseY = 0;
    if (s_MouseY > 1079) s_MouseY = 1079;
}

// ─── C-linkage API ────────────────────────────────────────────────────────────

extern "C" {

/// Initialise Circle's interrupt system, timer, and xHCI USB host controller.
/// Must be called once at kernel startup, after UART and framebuffer are up.
/// Returns 1 on success, 0 on failure.
int circle_usb_init(void) {
    if (!s_Interrupt.Initialize()) return 0;
    if (!s_Timer.Initialize())     return 0;
    if (!s_USBHCI.Initialize())    return 0;
    return 1;
}

/// Call this repeatedly from the main loop (task level).
/// Circle's plug-and-play system scans for newly connected devices here.
/// When a keyboard or mouse is found, it registers the callbacks.
void circle_usb_update(void) {
    boolean bUpdated = s_USBHCI.UpdatePlugAndPlay();

    // Try to bind keyboard if not yet bound
    if (bUpdated && s_pKeyboard == nullptr) {
        s_pKeyboard = (CUSBKeyboardDevice *)
            s_DeviceNameService.GetDevice("ukbd1", FALSE);
        if (s_pKeyboard != nullptr) {
            // Cooked mode: Circle translates HID keycodes to ASCII strings
            s_pKeyboard->RegisterKeyPressedHandler(KeyPressedHandler);
        }
    }

    // Try to bind mouse if not yet bound
    if (bUpdated && s_pMouse == nullptr) {
        s_pMouse = (CMouseDevice *)
            s_DeviceNameService.GetDevice("mouse1", FALSE);
        if (s_pMouse != nullptr) {
            // Raw mode: we get displacement values directly
            s_pMouse->RegisterStatusHandler(MouseStatusHandler);
        }
    }
}

/// Return the next ASCII character from the keyboard buffer.
/// Returns 0 if no character is available.
char circle_keyboard_getc(void) {
    return key_pop();
}

/// Returns 1 if a USB keyboard is currently connected and bound.
int circle_keyboard_ready(void) {
    return s_pKeyboard != nullptr ? 1 : 0;
}

/// Struct layout must match the MouseState struct in mouse.rs (Rust side).
struct CMouseState {
    unsigned buttons;
    int x;
    int y;
    int dx;
    int dy;
};

/// Fill the provided MouseState struct with the latest mouse position/buttons.
void circle_mouse_get_state(struct CMouseState *out) {
    if (!out) return;
    out->buttons = s_MouseButtons;
    out->x       = s_MouseX;
    out->y       = s_MouseY;
    out->dx      = s_MouseDX;
    out->dy      = s_MouseDY;
}

/// Returns 1 if a USB mouse is currently connected and bound.
int circle_mouse_ready(void) {
    return s_pMouse != nullptr ? 1 : 0;
}

/// Stub for assertion_failed — called when assert() fires in non-NDEBUG builds.
/// With -DNDEBUG all asserts are no-ops, but some object files may still have
/// a weak reference to this symbol. We provide a no-op stub so the link succeeds.
extern "C" void assertion_failed(const char *, const char *, unsigned) {
    // Do nothing — we compiled with -DNDEBUG so this should never be called.
    // If it is called anyway, silently continue rather than hanging.
    for (;;) {} // last-resort: infinite loop (visible as a hang, not a crash)
}

/// Circle's sysinit.cpp calls main() after running C++ constructors.
/// We don't use Circle's sysinit boot path (our Rust boot.S handles startup),
/// but sysinit.o is pulled in transitively and the linker requires this symbol.
/// Returning 0 causes sysinit to call halt() — which is fine because we never
/// actually reach this code path (our kernel_main() runs directly from boot.S).
int main(void) {
    return 0; // causes Circle's sysinit to call halt()
}

} // extern "C"
