[build]
target = "aarch64-unknown-none-softfloat"

[target.aarch64-unknown-none-softfloat]
linker = "aarch64-linux-gnu-gcc"
rustflags = ["-C", "link-arg=-nostartfiles", "-C", "link-arg=-nostdlib", "-C", "link-arg=-Tsrc/linker.ld"]
